Add a method to get known hashes of a target
php-tuf/php-tuf pull request #114
Opened 2021-02-25 20:53 UTC by phenaproxima

To get #113 done, we'll need a way to get the known hashes for a target. This adds a method for that to TargetsMetadata, plus test coverage.

2021-02-25 21:38 UTC, tedbow commented on tests/Metadata/TargetsMetadataTest.php
> +        $data[] = ["signed:targets:$target:hashes"];
could this to providerValidField also

2021-02-25 21:40 UTC, tedbow requested changes
looks good. just need to add `providerValidField` changes

2021-03-01 14:02 UTC, phenaproxima commented on tests/Metadata/TargetsMetadataTest.php
> +        $data[] = ["signed:targets:$target:hashes"];
Done!

2021-03-01 14:50 UTC, tedbow approved these changes
Great!

2021-03-01 14:51 UTC, merged