Relates to #265: Do not require consistent snapshots.
php-tuf/php-tuf pull request #269
Opened 2022-12-14 21:49 UTC by ergonlogic

2022-12-19 19:54 UTC, ergonlogic commented
This appears to force 'consistent snapshot' to be true. When we test this with `"consistent_snapshot": false,` in `1.root.json`, we get:

```
> pre-file-download: Tuf\ComposerIntegration\Plugin->preFileDownload
                                                                                       
  [Tuf\Exception\MetadataException]                                                    
  Object(ArrayObject)[signed][consistent_snapshot]:                                    
      This value should be equal to true. (code 478618a7-95ba-473d-9101-cabd45e49115)
```

2023-01-10 16:43 UTC, phenaproxima requested changes
I think that there are generally two things missing here: a generous sprinkling of comments, and test coverage.

2023-01-10 16:43 UTC, phenaproxima commented on src/Client/Updater.php
> +    private $rootMetadata;
Do we really need to keep the root metadata as a class property? I feel like this is a way to accidentally introduce side effects later.

2023-01-20 13:16 UTC, phenaproxima commented
Superseded by #278.

2023-01-20 13:16 UTC, closed without merging